### ISSUE TITLE
Feature: major version 

### ISSUE THREAD

**Issue by edgd1er** [dmvict/clean-workflow-runs#2]
Hello,

This suggestion is not about a bug but rather a small change to be sure to use the last version.

Context:
In order to always have the latest updated major version, github suggest to use name-of-action:v<major> unstead of specifying all major minor patch ver. I ve done such change on my workflows so i have the certitude of having all my workflows running with the latest versions.

I noticed that it didn t work for your action. After reading [Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions) on gh actions docs,  it appears the repo must have a v1 tag and this tag should moved to the last tag available. Let s say you have a tag v1. 0.1, the v1 would be at the same commit.

Would you be kind to place a v<major> on latest tag published?
Thanks.

**Comment by dmvict** [comment]
> Hello,
> 
> This suggestion is not about a bug but rather a small change to be sure to use the last version.
> 
> Context: In order to always have the latest updated major version, github suggest to use name-of-action:v unstead of specifying all major minor patch ver. I ve done such change on my workflows so i have the certitude of having all my workflows running with the latest versions.
> 
> I noticed that it didn t work for your action. After reading [Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions) on gh actions docs, it appears the repo must have a v1 tag and this tag should moved to the last tag available. Let s say you have a tag v1. 0.1, the v1 would be at the same commit.
> 
> Would you be kind to place a v on latest tag published? Thanks.

Thank you, @edgd1er. 

I've not read the page with recommended tag naming convention. 
So, I've added the tag `v1` just now. 
[v1](https://github.com/dmvict/clean-workflow-runs/releases/tag/v1).

**Comment by edgd1er** [comment]
@dmvict , Thanks you, Wokflows worked as expected with the new tag added. :+1:
