### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by Zehir** [dmvict/clean-workflow-runs#4]
Hello,

I just started to use this action and it's perfect but I get a warning message from github :

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: dmvict/clean-workflow-runs@v1.2.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

What can I do for it ?

**Comment by dmvict** [comment]
Hello, @Zehir 

Thank you for your issue. 
I will update the version of NodeJS for the very close time.

**Comment by dmvict** [comment]
@Zehir 

I've released the new version. Please, check it and close the issue if it is done.

**Comment by Zehir** [comment]
Perfect no more warnings thanks
